window:
  padding:
    x: 35
    y: 35

font:
  # The normal (roman) font face to use.
  normal:
    family: SF Mono
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: SF Mono
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: SF Mono
    # Style can be specified to pick a specific face.
    style: Italic
